blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index_blog, name='index'),
    url(r'^list/$', views.list_posts, name='list'),
    url(r'^list/(?P<pk>[0-9]+)/$', views.view_post, name='view'),
    url(r'^update/$', views.update_post, name='create'),
    url(r'^update/(?P<pk>[0-9]+)/$', views.update_post, name='update'),
    url(r'^delete/post/$', views.delete_post, name='delete_post'),
    url(r'^delete/comment/$', views.delete_comment, name='delete_comment'),
]

cafe/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from blog import urls as blog_url

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include(blog_url, namespace='blog')),
    url(r'^accounts/login/$', auth_views.login, {'template_name': 'login.html', }, name='login'),
    url(r'^accounts/logout/$', auth_views.logout, {'template_name': 'logout.html', }, name='logout'),
]

blog/models.py
from django.db import models
from django.conf import settings


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return 'Category {}: {}'.format(self.pk, self.name)


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    # writer = models.CharField(max_length=50)
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, null=True)

    category = models.ForeignKey(Category)
    tags = models.ManyToManyField('Tag', blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'Post {}: {}'.format(self.pk, self.title)


class Comment(models.Model):
    content = models.TextField(max_length=200)
    # writer = models.CharField(max_length=50)
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, null=True)

    post = models.ForeignKey(Post, null=True, blank=True)
    parent_comment = models.ForeignKey('Comment', null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'Comment {}: {}'.format(self.pk, self.content[:30])


class Tag(models.Model):
    name = models.CharField(max_length=30, db_index=True, unique=True)

    def __str__(self):
        return 'Tag {}: {}'.format(self.pk, self.name)

blog/forms.py
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = {'title', 'category', 'content', 'tags', }

blog/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger
from django.core.urlresolvers import reverse
from django.http import Http404
from django.contrib.auth.decorators import login_required

from .models import Category
from .models import Post
from .models import Comment
from .models import Tag


def index_blog(request):
    # URI: /blog/
    # blog 첫 화면
    return render(request, 'index.html')


def list_posts(request):
    # URI: /blog/list/
    # Post 들의 리스트 출력
    per_page = 5
    page = request.GET.get('page', 1)
    paginator = Paginator(Post.objects.all().order_by('-created_at'), per_page)

    try:
        posts_in_page = paginator.page(page)
    except EmptyPage:
        page = paginator.num_pages
        posts_in_page = paginator.page(page)
    except PageNotAnInteger:
        page = 1
        posts_in_page = paginator.page(page)

    paginator_info = {
        'post_in_page': posts_in_page,
        'page_current': int(page),
        'page_range': paginator.page_range,
        'has_previous': posts_in_page.has_previous(),
        'has_next': posts_in_page.has_next(),
    }

    message = request.GET.get('after_del')
    if message:
        message = 'Your post is deleted successfully.'

    return render(
        request,
        'list.html',
        {'page_info': paginator_info, 'message': message, }
    )


def view_post(request, pk):
    # URI: /blog/list/pk
    # GET: 1개의 Post 내용 출력, POST: 1개 Post 아래 댓글을 저장하고 다시 1개 Post 내용으로 Redirect
    post = get_object_or_404(Post, pk=pk)

    if request.method == 'GET':
        return render(request, 'view.html', {'post': post, })
    elif request.method == 'POST':
        # comment_writer = request.POST.get('comment_writer')

        @login_required
        def create_comment(request):
            comment_writer = request.user
            comment_content = request.POST.get('comment_content')

            # comment_writer, comment_content 중 빈 값이 있다면 등록하지 않는다.
            if comment_writer and comment_content:
                comment = Comment(
                    writer=comment_writer,
                    content=comment_content,
                    post=post
                )
                comment.save()

            return redirect(reverse('blog:view', kwargs={'pk': post.pk, }))

        return create_comment(request)


@login_required
def update_post(request, pk=None):
    # URI: /blog/update
    # GET: 글 등록/수정하는 페이지, pk 여부에 따라 등록인지 수정인지 판단한다.
    # POST: 글 등록/수정한 데이터 처리하는 페이지, pk 여부에 따라 등록인지 수정인지 판단한다.
    if request.method == 'GET':
        categories = Category.objects.all()

        if pk:
            post = Post.objects.get(pk=pk)
            return render(
                request,
                'update.html',
                {'categories': categories, 'post': post, }
            )
        else:
            return render(
                request,
                'update.html',
                {'categories': categories, }
            )
    elif request.method == 'POST':
        # 필수 데이터들의 유효성을 확인한다. 오류가 발생하면 404 페이지로 redirect 한다.
        try:
            title = request.POST.get('post_title')
            category = Category.objects.get(
                pk=int(request.POST.get('post_category'))
            )
            # writer = request.POST.get('post_writer')
            writer = request.user
            content = request.POST.get('post_content')
        except:
            raise Http404('Necessary info to upload post is insufficient.')

        # title, category, writer, content 중 하나라도 없다면 등록하지 않고 리스트 화면으로 간다.
        if title and category and writer and content:
            tags = list(
                map(str.strip, request.POST.get('post_tags', '').split(','))
            )

            # pk 가 있다면 기존 post 에서 불러오고, 없다면 방금 입력된 내용으로 post 를 만든다.
            if pk:
                post = Post.objects.get(pk=pk)

                for post_tag in post.tags.all():
                    post.tags.remove(post_tag)

                post.title, post.category = title, category
                post.writer, post.content = writer, content
            else:
                post = Post(
                    title=title,
                    category=category,
                    writer=writer,
                    content=content
                )

            post.save()

            # tag 를 만들고, post 에 연결한다.
            for tag_name in tags:
                if not Tag.objects.filter(name=tag_name).exists():
                    tag = Tag(name=tag_name)
                    tag.save()
                else:
                    tag = Tag.objects.filter(name=tag_name).first()

                post.tags.add(tag)

            return redirect(reverse('blog:view', kwargs={'pk': post.pk, }))
        else:
            return redirect(reverse('blog:list'))


@login_required
def delete_post(request):
    # URI: /blog/delete/post
    # 1개 Post 삭제하고 리스트 화면으로 Redirect
    pk = request.GET.get('pk', None)

    if pk:
        post = Post.objects.get(pk=pk)
        post.delete()

    return redirect(reverse('blog:list')+'?after_del=True')


@login_required
def delete_comment(request):
    # URI: /blog/delete/comment
    # 1개 Comment 삭제하고 Post 조회 화면으로 Redirect
    pk = request.GET.get('pk', None)
    post_pk = None

    if pk:
        comment = Comment.objects.get(pk=pk)
        post_pk = comment.post.pk
        comment.delete()

    return redirect(reverse('blog:view', kwargs={'pk': post_pk, }))

blog/templates/blog_base.html
<!DOCTYPE html>
<html lang="kr">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Blog Application{% endblock title %}</title>

    {% load staticfiles %}
    <!-- Bootstrap & Flat UI & jQuery import -->
    <script src="{% static 'js/vendor/jquery.min.js' %}"></script>
    <script src="{% static 'js/flat-ui.min.js' %}"></script>

    <link href="{% static 'css/vendor/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/flat-ui.css' %}" rel="stylesheet">
</head>
<body>
    {% block login_form %}
    <div class="modal fade" tabindex="-1" role="dialog" id="login">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form method="POST" action="{% url 'login' %}">
                {% csrf_token %}
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title">Please sign in</h4>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <input type="text" class="form-control login-field" placeholder="Enter your name" id="username" name="username" />
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control login-field" placeholder="Password" id="password" name="password" />
                        </div>
                        <div class="form-group">
                            <input type="hidden" name="next" value="{{ request.get_full_path }}" />
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Sign in</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% endblock login_form %}

    {% block user %}
    <div class="row">
        <div class="col-md-12" align="right">
            <div class="page-header">
            {% if request.user.id %}
                Hello, {{ request.user.username }}!
            {% endif %}
            &nbsp;&nbsp;&nbsp;&nbsp;
            {% if request.user.id %}
                <a href="{% url 'logout' %}">Sign out</a>
            {% else %}
                <a data-toggle="modal" data-target="#login">Sign in</a>
            {% endif %}
            &nbsp;&nbsp;&nbsp;&nbsp;
            </div>
        </div>
    </div>
    {% endblock user %}
    <!-- Content -->
    {% block contents %}

    {% endblock contents %}
</body>
</html>

blog/templates/comment.html
        {# Post variable is needed! #}
        <!-- Comments Output -->
        <div class="row">
            <div class="col-md-12">
                <h4>Comments</h4>
                <dl class="dl-horizontal">
                    {% for comment in post.comment_set.all %}
                    <dt>{{ comment.writer|safe }}</dt>
                    <dd>{{ comment.content|safe }}
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <a href="{% url 'blog:delete_comment' %}?pk={{ comment.pk }}"><span class="fui-cross"></span></a>
                    </dd>
                    {% empty %}
                    <dt></dt>
                    <dd>Please be the first comment-er!</dd>
                    {% endfor %}
                </dl>
            </div>
        </div>
        <!-- Comment Input -->
        <div class="row">
            <div class="col-md-12">
                <dl class="dl-horizontal">
                    <form method="POST" action="{% url 'blog:view' post.pk %}">
                        {% csrf_token %}
                        <dt class="form-group"><input type="text" value placeholder="Your name" class="form-control" name="comment_writer"></dt>
                        <dd class="form-group"><textarea value placeholder="Comment here" class="form-control" name="comment_content"></textarea></dd>
                        <div align="right" class="form-group">
                            <input type="submit" value="Save Comment" class="btn btn-primary" />
                        </div>
                    </form>
                </dl>
            </div>
        </div>

blog/templates/index.html
{% extends "blog_base.html" %}

{% block contents %}
    <div class="container-fluid">
        <!-- Hello, world! -->
        <div class="row">
            <div class="col-md-12">
                <div class="inner cover">
                    <h1 class="cover-heading">Hello, world!</h1>
                    <br />
                    <p class="lead">Here is the first view & template application of Django. It's little bit difficult, but very interesting.</p>
                    <p class="lead">Click <strong></strong></string><a href="{% url "blog:list" %}">HERE</a></strong> to see the list of posts.</p>
                </div>
                <div class="mastfoot">
                    <div class="inner" align="middle">
                        <p>Cover template for Bootstrap</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock contents %}

blog/templates/list.html
{% extends "blog_base.html" %}

{% block contents %}
    <div class="container-fluid">
        <!-- Message -->
        {% if message %}
        {% load static %}
        <script src="{% static 'js/message.js' %}"></script>

        <div class="row" id="message">
            <div class="col-md-12">
                <div class="alert alert-dismissable alert-warning">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    {{ message }}
                </div>
            </div>
        </div>
        {% endif %}
        <!-- Button -->
        <div class="row">
            <div class="col-md-12">
                <div class="form-group" align="right">
                    <a href="{% url 'blog:create' %}" type="submit" class="btn btn-primary">Write a New Post</a>
                </div>
            </div>
        </div>
        <!-- List of posts -->
        {% for post in page_info.post_in_page %}
        <div class="row">
            <div class="col-md-12">
                <h4><a href="{% url "blog:view" post.pk %}">{{ post.title }}</a></h4>
                <dl class="dl-horizontal">
                    <dt>Category</dt>
                    <dd>{{ post.category.name|safe }}</dd>
                    <dt>Writer</dt>
                    <dd>{{ post.writer|safe }}</dd>
                    <dt>Created at</dt>
                    <dd>{{ post.created_at|date:"Y/m/j H:i" }}</dd>
                </dl>
                <pre style="border-width: 0"><p>{{ post.content|slice:"0:100"|add:" ..."|safe|escape }}</p></pre>
            </div>
        </div>
        <br>
        {% empty %}
        <div class="row">
            <div class="col-md-12">
                <h3>No post!</h3>
            </div>
        </div>
        <br>
        {% endfor %}
        <!-- Paginator -->
        <div class="row">
            <div class="col-md-12 pagination pagination-lg" align="middle">
                <ul>
                    <li class="previous{% if not page_info.has_previous %} disabled{% endif %}"><a {% if page_info.has_previous %}href="?page={{ page_info.page_current|add:'-1' }}"{% endif %} class="fui-arrow-left"></a></li>
                    {% for page in page_info.page_range %}
                        <li{% if page == page_info.page_current %} class="active"{% endif %}><a href="{% if page == page_info.page_current %}#{% else %}?page={{ page }}{% endif %}">{{ page }}</a></li>
                    {% endfor %}
                    <li class="next{% if not page_info.has_next %} disabled{% endif %}"><a {% if page_info.has_next %}href="?page={{ page_info.page_current|add:'1' }}"{% endif %} class="fui-arrow-right"></a></li>
                </ul>
            </div>
        </div>
    </div>
{% endblock contents %}

blog/templates/tags.html
        {# Post variable is needed! #}
        <!-- Tags Output -->
        <div class="row">
            <div class="col-md-12">
                <h4>Tags</h4>
                <ul class="list-inline">
                    {% for tag in post.tags.all %}
                        <li>{{ tag.name }}</li>
                    {% empty %}
                    No tags in this post.
                    {% endfor %}
                </ul>
            </div>
        </div>

blog/templates/update.html
{% extends "blog_base.html" %}

{% block contents %}
    <div class="container-fluid">
        <!-- Post form -->
        <div class="row">
            <div class="col-md-12">
                {# Post Update #}
                {% if post %}
                <form role="form" method="POST" action="{% url 'blog:update' post.pk %}">
                {# Post Register #}
                {% else %}
                <form role="form" method="POST" action="{% url 'blog:create' %}">
                {% endif %}
                {% csrf_token %}
                    <div class="form-group">
                        <label for="post_title_input">Title</label>
                        <input type="text" class="form-control" name="post_title" value="{{ post.title }}" />
                    </div>
                    <div class="form-group">
                        <label for="post_category_input">Category</label>
                        <select class="form-control" name="post_category">
                            {% for category in categories %}
                            <option value="{{ category.pk }}" {% if category == post.category %}selected{% endif %}>{{ category.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="post_writer_input">Writer</label>
                        <input type="text" class="form-control" name="post_writer" value="{{ post.writer }}" />
                    </div>
                    <div class="form-group">
                        <label for="post_content_input">Content</label>
                        <textarea value class="form-control" rows="15" name="post_content">{{ post.content }}</textarea>
                    </div>
                    <div class="form-group tagsinput-default">
                        <label for="post_tags_input">Tags</label>
                        <input name="post_tags" class="bootstrap-tagsinput" data-role="tagsinput" value="{% for tag in post.tags.all %}{{ tag.name }}{% if not forloop.last %}, {% endif %}{% endfor %}" />
                    </div>
                    <div class="form-group" align="right">
                        {% if post %}
                        <a href="{% url 'blog:view' post.pk %}" type="submit" class="btn btn-danger">Cancel</a>
                        {% else %}
                        <a href="{% url 'blog:list' %}" type="submit" class="btn btn-danger">Cancel</a>
                        {% endif %}
                        <button type="submit" class="btn btn-primary">Save Post</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock contents %}

blog/templates/view.html
{% extends "blog_base.html" %}

{% block contents %}
    <div class="container-fluid">
        <!-- Delete Confirm -->
        <div class="modal fade" tabindex="-1" role="dialog" id="delete-confirm">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title">Delete Confirmation</h4>
                    </div>
                    <div class="modal-body">
                        <p>Do you want to delete really?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <a href="{% url 'blog:delete_post' %}?pk={{ post.pk }}"><button type="button" class="btn btn-danger">Delete</button></a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Buttons -->
        <div class="row">
            <div class="col-md-6" align="left">
                <a href="{% url 'blog:list' %}" class="btn btn-warning">See the List</a>
            </div>
            <div class="col-md-6" align="right">
                <a href="{% url 'blog:update' post.pk %}" class="btn btn-primary">Update this Post</a>
                <a class="btn btn-danger" data-toggle="modal" data-target="#delete-confirm">Delete this Post</a>
            </div>
        </div>
        <!-- Post -->
        <div class="row">
            <div class="col-md-12">
                <h3>{{ post.title }}</h3>
                <dl class="dl-horizontal">
                    <dt>Category</dt>
                    <dd>{{ post.category.name|safe }}</dd>
                    <dt>Writer</dt>
                    <dd>{{ post.writer|safe }}</dd>
                    <dt>Created at</dt>
                    <dd>{{ post.created_at|date:"Y/m/j H:i" }}</dd>
                </dl>
                <pre style="border-width: 0"><p>{{ post.content|slice:"0:800"|safe }}</p></pre>
            </div>
        </div>
        <!-- Tags -->
        {% include "tags.html" %}
        <br />
        <!-- Comments -->
        {% include "comment.html" %}
    </div>

    {% load static %}
    <script src="{% static 'js/view.js' %}"></script>
{% endblock contents %}

templates/login.html
<!DOCTYPE html>
<html lang="kr">
<head>
    <meta charset="utf-8">

    <title>Sign in</title>

    <!-- Bootstrap core CSS -->
    {% load staticfiles %}
    <!-- Bootstrap & Flat UI & jQuery import -->
    <script src="{% static 'js/vendor/jquery.min.js' %}"></script>
    <script src="{% static 'js/flat-ui.min.js' %}"></script>

    <link href="{% static 'css/vendor/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/flat-ui.css' %}" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-3">&nbsp;</div>
            <div class="col-md-6">
                <form method="POST" action="{% url 'login' %}" class="form-signin">
                    {% csrf_token %}
                    <div>
                        <h2 class="form-signin-heading">Please sign in</h2>
                    </div>
                    <div class="form-group">
                        <label for="inputName" class="sr-only">Write your name</label>
                        <input type="text" id="inputName" class="form-control" placeholder="Write your name" required autofocus name="username" value="{{ request.POST.username }}">
                    </div>
                    <div class="form-group">
                        <label for="inputPassword" class="sr-only">Password</label>
                        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required name="password">
                    </div>
                    <div>
                        <input type="hidden" name="next" value="{% if next %}{{ next }}{% else %}{% url 'blog:index' %}{% endif %}" />
                    </div>
                    <div class="form=group" align="right">
                        <button type="submit" class="btn btn-lg btn-primary btn-block">Sign in</button>
                    </div>
                </form>
            </div>
            <div class="col-md-3">&nbsp;</div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12" align="center">
            {% if form.errors %}
            <p></p>
            <p>Your username and password didn't match. Please try again.</p>
            {% endif %}
        </div>
    </div>
</body>
</html>

templates/logout.html
<!DOCTYPE html>
<html lang="kr">
<head>
    <meta charset="utf-8">

    <title>Sign out</title>

    <!-- Bootstrap core CSS -->
    {% load staticfiles %}
    <!-- Bootstrap & Flat UI & jQuery import -->
    <script src="{% static 'js/vendor/jquery.min.js' %}"></script>
    <script src="{% static 'js/flat-ui.min.js' %}"></script>

    <link href="{% static 'css/vendor/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/flat-ui.css' %}" rel="stylesheet">
</head>
<body>
    {{ form.errors }}
    {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
    {% endif %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                {% if not request.user.is_authenticated %}
                <h3>You signed out!</h3>
                {% endif %}
            </div>
            <div class="col-md-12">
                <a href="{% url 'blog:index' %}">Go to the first page</a>
            </div>
        </div>
    </div>
</body>
</html>